name: BD_RICM_Lib

channels:
    - conda-forge

dependencies:
    - python>=3.8
    - pip
    - numpy
    - joblib
    - scikit-image
    - scipy
    - matplotlib-base
    - pystackreg
    - tensorflow



