name: BD_RICMlib

channels:
    - conda-forge

dependencies:
    - python>=3.8
    - spyder
    - numpy
    - joblib
    - scikit-image
    - scipy
    - matplotlib-base
    - pystackreg
    - tensorflow

